### ISSUE TITLE
Add default keycloak configuration

### ISSUE THREAD

**Issue by thomasdarimont** [thomasdarimont/embedded-spring-boot-keycloak-server#24]
To ease the usage of the starter we should ship with a set of reasonable default configuration for Keycloak.

Tasks:
- Include a default keycloak configuration
- If no admin user password is configured, generate a random password and print it to the console like spring security does.

A default keycloak configuration could look like this:
```yml
keycloak:
  hostname:
    provider: "default"
    default:
      frontendUrl: ""
      adminUrl: ""
      forceBackendUrlToFrontendUrl: false

  admin:
    realm: "master"

  eventsStore:
    provider: "jpa"

  eventsListener:
    "jboss-logging":
      "success-level": "info"
      "error-level": "warn"

  realm:
    provider: "jpa"

  user:
    provider: "jpa"

  userFederatedStorage:
    provider: "jpa"

  userSessionPersister:
    provider: "jpa"

  authorizationPersister:
    provider: "jpa"

  userCache:
    default:
      enabled: true

  timer:
    provider: "basic"

  theme:
    staticMaxAge: "2592000"
    cacheTemplates: true
    cacheThemes: true
    folder:
      dir: ""

  scheduled:
    interval: 900

  connectionsHttpClient:
    default: {}

  connectionsJpa:
    provider: "default"
    default:
      dataSource: "spring/datasource"
      initializeEmpty: true
      migrationStrategy: "update"
      showSql: false
      formatSql: true
      globalStatsInterval: -1

  realmCache:
    default:
      enabled: true

  connectionsInfinispan:
    default:
      jgroupsUdpMcastAddr: "234.56.78.90"
      nodeName: "localhost"
      siteName: ""
      clustered: fase
      async: false
      sessionsOwners: 1
      l1Lifespan: 600000
      remoteStoreEnabled: false
      remoteStoreHost: "localhost"
      remoteStorePort: 11222
      hotrodProtocolVersion: ""

  scripting: {}

  "jta-lookup":
    provider: "jboss"
    jboss:
      enabled: true

  "login-protocol":
    "saml":
      "knownProtocols": ["http=${server.port}", "https=${server.port}"]

  "x509cert-lookup":
    provider: "default"
    default:
      enabled: true

      haproxy:
        enabled: true
        sslClientCert: "x-ssl-client-cert"
        sslCertChainPrefix: "x-ssl-client-cert-chain"
        certificateChainLength: 1

      apache:
        enabled: true
        sslClientCert: "x-ssl-client-cert"
        sslCertChainPrefix: "x-ssl-client-cert-chain"
        certificateChainLength: 1

      nginx:
        enabled: true
        sslClientCert: "x-ssl-client-cert"
        sslCertChainPrefix: "x-ssl-client-cert-chain"
        certificateChainLength: 1
```
